# Generated by Django 3.2.4 on 2021-06-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото профиля'),
            preserve_default=False,
        ),
    ]
