# Generated by Django 3.2.4 on 2021-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210625_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_ids',
            field=models.TextField(blank=True, null=True, verbose_name='ID видео с youtube через ","'),
        ),
    ]
