export const USER_SIGN_UP_START_ACTION = 'USER_SIGN_UP_START_ACTION'
export const USER_SIGN_UP_SUCCESS_ACTION = 'USER_SIGN_UP_SUCCESS_ACTION'
export const USER_SIGN_UP_ERROR_ACTION = 'USER_SIGN_UP_ERROR_ACTION'

export const USER_LOGIN_START_ACTION = 'USER_LOGIN_START_ACTION'
export const USER_LOGIN_SUCCESS_ACTION = 'USER_LOGIN_SUCCESS_ACTION'
export const USER_LOGIN_ERROR_ACTION = 'USER_LOGIN_ERROR_ACTION'

export const USER_ME_START_ACTION = 'USER_ME_START_ACTION'
export const USER_ME_FINISH_ACTION = 'USER_ME_FINISH_ACTION'
export const USER_ME_ANONYMOUS_ACTION = 'USER_ME_ANONYMOUS_ACTION'

export const USER_ME_UPDATE_START_ACTION = 'USER_ME_UPDATE_START_ACTION'
export const USER_ME_UPDATE_SUCCESS_ACTION = 'USER_ME_UPDATE_SUCCESS_ACTION'
export const USER_ME_UPDATE_ERROR_ACTION = 'USER_ME_UPDATE_ERROR_ACTION'

export const USER_LIST_FETCH_START_ACTION = 'USER_LIST_FETCH_START_ACTION'
export const USER_LIST_FETCH_FINISH_ACTION = 'USER_LIST_FETCH_FINISH_ACTION'
export const USER_LIST_SET_FILTERS_ACTION = 'USER_LIST_SET_FILTERS_ACTION'

export const USER_FETCH_START_ACTION = 'USER_FETCH_START_ACTION'
export const USER_FETCH_FINISH_ACTION = 'USER_FETCH_FINISH_ACTION'

export const INSTRUMENT_LIST_FETCH_START_ACTION = 'INSTRUMENT_LIST_FETCH_START_ACTION'
export const INSTRUMENT_LIST_FETCH_FINISH_ACTION = 'INSTRUMENT_LIST_FETCH_FINISH_ACTION'

export const GENRE_LIST_FETCH_START_ACTION = 'GENRE_LIST_FETCH_START_ACTION'
export const GENRE_LIST_FETCH_FINISH_ACTION = 'GENRE_LIST_FETCH_FINISH_ACTION'